service: test-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  test:
    handler: Test.handler
    memorySize: 128
    description: Submit candidate information and starts interview process.
    events:
      - http: 
          path: test
          method: post